name: Test deployment via SSH-Action
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up secret file
      env:
        WPDEVELOPER: ${{ secrets.WPDEVELOPER }}
      run: |
        echo $WPDEVELOPER >> secrets.txt
#    - name: Run tmate
#      uses: mxschmitt/action-tmate@v2
    - name: Deploy and build via SSH 
      uses: appleboy/ssh-action@master
      with:
        host: 3.71.197.174
        username: himanshu
        key: ${{ secrets.WPDEVELOPER }}
        port: 22
        script: |
          ls -la
          echo "complete"
