name: Deploy to next-release branch via SSH-Action
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy and build via SSH 
      uses: appleboy/ssh-action@master
      with:
        host: 18.184.220.245
        username: bitnami
        key: ${{ secrets.STAGING_DEPLOY_KEY }}
        port: 22
        script: |
          ls -la
          echo "complete"
